# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modeified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collegesite.TimeStampedModel')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('department', models.CharField(choices=[('CE', 'Civil Engineering'), ('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics Communtication Engineering'), ('EEE', 'Electronics Electrical Engineering'), ('ME', 'Mechanical Engineering')], max_length=3)),
                ('profilepic', models.ImageField(upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('collegesite.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collegesite.TimeStampedModel')),
                ('father', models.CharField(max_length=40)),
                ('mother', models.CharField(max_length=40)),
                ('profilepic', models.ImageField(upload_to=b'')),
            ],
            bases=('collegesite.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Studentapplication',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collegesite.TimeStampedModel')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('department', models.CharField(choices=[('CE', 'Civil Engineering'), ('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics Communtication Engineering'), ('EEE', 'Electronics Electrical Engineering'), ('ME', 'Mechanical Engineering')], max_length=3)),
                ('sccmemo', models.FileField(upload_to=b'')),
                ('intermemo', models.FileField(upload_to=b'')),
                ('address', models.TextField(max_length=100)),
                ('nationality', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            bases=('collegesite.timestampedmodel',),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collegesite.Studentapplication'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
