# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='collegesite.Studentapplication'),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestampedmodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='collegesite.TimeStampedModel'),
        ),
    ]
